name: local tests

on:
  push:
    branches:
      - main
      - staging*
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.8"
          - "3.10"
        platform:
          - ubuntu-latest
        # include:
        #   - platform: macos-latest
        #     python: "3.9"
    runs-on: ${{ matrix.platform }}
    name: Run local integration tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python and mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python }}
            mamba

      - name: Set channel priority
        shell: bash -l {0}
        run: conda config --set channel_priority strict

      - name: Install showyourwork
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[tests]"

      - name: Run local integration tests
        shell: bash -l {0}
        run: python -m pytest tests/integration
