name: publish

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  build:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.10"

      - name: Build sdist
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: ${{ github.event.inputs.version }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m build

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*

  upload_pypi:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.8.5
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_KEY }}
