name: remote tests

on:
  push:
    branches:
      - main
      - staging*
  pull_request_target:
    types: [labeled]
  merge_group:

jobs:
  tests:
    if: ${{ (github.event_name == 'push' && github.repository == 'showyourwork/showyourwork') || (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to test')) }}
    runs-on: ubuntu-latest
    name: Run remote integration tests
    concurrency: showyourwork-remote
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        showyourwork-spec:
          - ${{ (github.event_name == 'push' && format('git+https://github.com/showyourwork/showyourwork.git@{0}#egg=showyourwork', github.sha)) || format('git+{0}@{1}#egg=showyourwork', github.event.pull_request.head.repo.clone_url, github.event.pull_request.head.sha) }}
    steps:
      - name: Remove `safe to test` label
        if: ${{ (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to test')) }}
        uses: andymckay/labeler@3a4296e9dcdf9576b0456050db78cfd34853f260
        with:
          remove-labels: "safe to test"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python and mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          create-args: >-
            python=3.9
            mamba

      - name: Install showyourwork
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install -e "${{ matrix.showyourwork-spec }}[tests]"

      - name: Run remote integration tests
        shell: bash -l {0}
        run: python -m pytest --remote -m "remote" tests/integration --action-spec ${{ matrix.showyourwork-spec }}
        env:
          SANDBOX_TOKEN: ${{ secrets.SANDBOX_TOKEN }}
          OVERLEAF_EMAIL: ${{ secrets.OVERLEAF_EMAIL }}
          OVERLEAF_PASSWORD: ${{ secrets.OVERLEAF_PASSWORD }}
          GH_API_KEY: ${{ secrets.GH_API_KEY }}
