name: remote tests

on:
  push:
    branches:
      - main
      - staging
  pull_request_target:
    types: [labeled]

jobs:
  tests:
    if: ${{ (github.event_name == 'push' && github.repository == 'showyourwork/showyourwork') || (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to test')) }}
    runs-on: ubuntu-latest
    name: Run remote integration tests
    concurrency: showyourwork-remote
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        workflow-version:
          - ${{ (github.event_name == 'push' && github.sha) || format('{0}@{1}', github.event.pull_request.head.repo.clone_url, github.event.pull_request.head.sha) }}
          - 0.3.1
        action-spec:
          - ${{ (github.event_name == 'push' && format('git+https://github.com/showyourwork/showyourwork.git@{0}#egg=showyourwork', github.sha)) || format('git+{0}@{1}#egg=showyourwork', github.event.pull_request.head.repo.clone_url, github.event.pull_request.head.sha) }}
    steps:
      - name: Remove `safe to test` label
        if: ${{ (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to test')) }}
        uses: andymckay/labeler@3a4296e9dcdf9576b0456050db78cfd34853f260
        with:
          remove-labels: "safe to test"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.9"

      - name: Install showyourwork
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[tests]"

      - name: Run remote integration tests
        shell: bash -l {0}
        run: python -m pytest --remote -m "remote" tests/integration --workflow-version ${{ matrix.workflow-version }} --action-spec ${{ matrix.action-spec }}
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
          SANDBOX_TOKEN: ${{ secrets.SANDBOX_TOKEN }}
          OVERLEAF_EMAIL: ${{ secrets.OVERLEAF_EMAIL }}
          OVERLEAF_PASSWORD: ${{ secrets.OVERLEAF_PASSWORD }}
          GH_API_KEY: ${{ secrets.GH_API_KEY }}
