name: unit tests

on:
  push:
    branches:
      - main
      - staging*
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.8"
          - "3.11"
        platform:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
        exclude:
          - platform: macos-latest
            python: "3.8"
          # - platform: windows-latest
          #   python: "3.8"
    runs-on: ${{ matrix.platform }}
    name: Run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python and mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          create-args: >-
            python=${{ matrix.python }}
            mamba

      - name: Install showyourwork
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[tests]"

      - name: Run tests
        shell: bash -l {0}
        run: |
          python -m pytest tests/unit
